// Seed content, kept apart from the seeding side effect so tests can import
// and check it without touching the database.

// Gallery data — IDs after seed: 1=Toma Control, 2=Caribbean Cinemas, 3=Humanos Seguros,
// 4=IAMBICA, 5=Alaver, 6=Aguavida, 7=Cara Hueca 34hz, 8=Tela de Pesca.
// Positional: the seed resets sqlite_sequence, so inserting anywhere but the end
// renumbers everything after it and silently repoints projects at the wrong piece.
const gallery = [
{
    image: 'toma-control-flyer.webp',
    video: '/videos/toma-control-recap.mp4',
    title_en: 'Toma Control', title_es: 'Toma Control',
    category_en: 'Interactive Event', category_es: 'Evento Interactivo',
    year: '2024',
    desc_en: 'An immersive audiovisual party where participants shape sound and image in real time through interactive stations with voice and electronic instruments, generating live oscilloscope-based visuals. Built with TouchDesigner, MaxMSP, and Pure Data.',
    desc_es: 'Una fiesta audiovisual inmersiva donde los participantes moldean sonido e imagen en tiempo real a través de estaciones interactivas con voz e instrumentos electrónicos, generando visuales en vivo basados en osciloscopio. Construido con TouchDesigner, MaxMSP y Pure Data.',
  },
{
    image: '/uploads/1774712099411-unnamed.png',
    video: 'https://www.youtube.com/watch?v=8saunvDlCIk',
    title_en: 'Caribbean Cinemas Policy Trailer', title_es: 'Tráiler de Políticas Caribbean Cinemas',
    category_en: 'Sound Design', category_es: 'Diseño Sonoro',
    year: '2022',
    desc_en: 'Sound design and audio implementation for the Caribbean Cinemas policy trailer, created in collaboration with Paleta Creativa.',
    desc_es: 'Diseño sonoro e implementación de audio para el tráiler de políticas de Caribbean Cinemas, creado en colaboración con Paleta Creativa.',
  },
{
    image: '/uploads/1774711659996-unnamed-(1).png',
    video: 'https://www.youtube.com/watch?v=ei6vcByEARU&list=RDei6vcByEARU&start_radio=1',
    title_en: 'Humanos Seguros Commercial', title_es: 'Anuncio Humanos Seguro',
    category_en: 'Audio', category_es: 'Audio',
    year: '2024',
    desc_en: 'Sound design and audio implementation for the Humanos Seguros 2024 commercial, created in collaboration with Adelobo Estudios.',
    desc_es: 'Diseño de sonido e implementación de audio para el anuncio publicitario de Humanos Seguros 2024, creado en colaboración con Adelobo Estudios.',
  },
{
    image: 'iambica-logo.svg',
    title_en: 'IAMBICA', title_es: 'IAMBICA',
    category_en: 'In Progress', category_es: 'En progreso',
    year: '2026',
    desc_en: 'Interactive web platform for a new media art festival. Real-time audience participation via mobile devices, with OSC integration for audiovisual systems.',
    desc_es: 'Plataforma web interactiva para un festival de new media art. Participación del público en tiempo real a través de dispositivos móviles, con integración OSC para sistemas audiovisuales.',
  },
{
    image: 'alaver-logo.svg',
    video: 'https://www.instagram.com/reel/DA-3Y_Sv0R_/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==',
    title_en: 'Alaver Commercial', title_es: 'Anuncio Alaver',
    category_en: 'Audio', category_es: 'Audio',
    year: '2024',
    desc_en: 'Sound design and audio implementation for the Alaver 2024 commercial, created in collaboration with Adelobo Estudios.',
    desc_es: 'Diseño de sonido e implementación de audio para el anuncio publicitario de Alaver 2024, creado en colaboración con Adelobo Estudios.',
  },
{
    image: 'cyanea.webp',
    video: 'https://vimeo.com/1186513976',
    title_en: 'Aguavida', title_es: 'Aguavida',
    category_en: 'Sound Art', category_es: 'Arte Sonoro',
    year: '2026',
    desc_en: 'Processed equation: x(t) = cos(t), y(t) = sin(t). Let’s protect our waters and the lives that belong to them.',
    desc_es: 'Ecuación procesada: x(t) = cos(t), y(t) = sin(t). Cuidemos nuestras aguas y las vidas que les pertenece.',
  },
{
    image: 'cara-hueca-34hz.webp',
    video: 'https://vimeo.com/1144271175',
    title_en: 'Cara Hueca 34hz', title_es: 'Cara Hueca 34hz',
    category_en: 'Sound Art', category_es: 'Arte Sonoro',
    year: '2026',
    desc_en: 'Rotating face vector. Stabilized at 35.1424hz.',
    desc_es: 'Vector de cara en rotación. Estabilizado a 35.1424hz.',
  },
{
    image: 'orca.webp',
    video: 'https://vimeo.com/1144271321',
    title_en: 'Tela de Pesca', title_es: 'Tela de Pesca',
    category_en: 'Sound Art', category_es: 'Arte Sonoro',
    year: '2026',
    desc_en: 'Processed equation: v.y = cos · 3 · π, v.x = sin · 2 · π. Let’s protect our waters and the lives that belong to them.',
    desc_es: 'Ecuación procesada: v.y = cos · 3 · π, v.x = sin · 2 · π. Cuidemos nuestras aguas y las vidas que les pertenece.',
  },
];

// Projects data — grouped by category, with gallery_id references
const projects = [
  // --- Interactive ---
  {
    name_en: 'IAMBICA', name_es: 'IAMBICA',
    desc_en: 'Interactive web platform for a new media art festival. Real-time audience participation via mobile devices, with OSC integration for audiovisual systems.',
    desc_es: 'Plataforma web interactiva para un festival de new media art. Participación del público en tiempo real a través de dispositivos móviles, con integración OSC para sistemas audiovisuales.',
    status_en: 'In Progress', status_es: 'En Progreso',
    stack: JSON.stringify(['React 19', 'p5.js', 'WebSockets', 'OSC', 'Express', 'SQLite', 'Web Audio API']),
    category_en: 'Interactive', category_es: 'Interactivo',
    gallery_id: 4,
  },
  {
    name_en: 'Toma Control', name_es: 'Toma Control',
    desc_en: 'An immersive audiovisual party where participants shape sound and image in real time through interactive stations.',
    desc_es: 'Una fiesta audiovisual inmersiva donde los participantes moldean sonido e imagen en tiempo real a través de estaciones interactivas.',
    status_en: '2024', status_es: '2024',
    stack: JSON.stringify(['TouchDesigner', 'MaxMSP', 'Pure Data']),
    category_en: 'Interactive', category_es: 'Interactivo',
    gallery_id: 1,
  },
  // --- Audio ---
  {
    name_en: 'Humanos Seguros Commercial', name_es: 'Anuncio Humanos Seguros',
    desc_en: 'Sound design and audio implementation for the Humanos Seguros 2024 commercial, created in collaboration with Adelobo Estudios.',
    desc_es: 'Diseño de sonido e implementación de audio para el anuncio publicitario de Humanos Seguros 2024, creado en colaboración con Adelobo Estudios.',
    status_en: '2024', status_es: '2024',
    stack: JSON.stringify(['Ableton Live', 'Logic', 'Pro Tools', 'Foley']),
    category_en: 'Audio', category_es: 'Audio',
    gallery_id: 3,
  },
  {
    name_en: 'Caribbean Cinemas Policy Trailer', name_es: 'Tráiler de Políticas Caribbean Cinemas',
    desc_en: 'Sound design and audio implementation for the Caribbean Cinemas policy trailer, created in collaboration with Paleta Creativa.',
    desc_es: 'Diseño sonoro e implementación de audio para el tráiler de políticas de Caribbean Cinemas, creado en colaboración con Paleta Creativa.',
    status_en: '2022', status_es: '2022',
    stack: JSON.stringify(['Sound Design', 'Pro Tools', 'Foley']),
    category_en: 'Audio', category_es: 'Audio',
    gallery_id: 2,
  },
  {
    name_en: 'Alaver Commercial', name_es: 'Anuncio Alaver',
    desc_en: 'Sound design and audio implementation for the Alaver 2024 commercial, created in collaboration with Adelobo Estudios.',
    desc_es: 'Diseño de sonido e implementación de audio para el anuncio publicitario de Alaver 2024, creado en colaboración con Adelobo Estudios.',
    status_en: '2024', status_es: '2024',
    stack: JSON.stringify(['Sound Design', 'Pro Tools', 'Foley']),
    category_en: 'Audio', category_es: 'Audio',
    gallery_id: 5,
  },
  // --- Audio Software ---
  {
    name_en: 'cumple', name_es: 'cumple',
    desc_en: 'Delivery QC for audio: a CLI, a watch folder and a desktop app for macOS, Windows and Linux that measure a mix against Netflix, Amazon, Disney+, EBU R 128 or cinema trailer specs, name the clause that fails, quote it and suggest the fix. BS.1770-5 loudness and true-peak meters written from the standard, passing all 29 EBU test cases; 39 destination profiles, 190 tests, and an audio diff that reports offset, gain, polarity and residual.',
    desc_es: 'Control de calidad de entregas de audio: un CLI, una carpeta vigilada y una app de escritorio para macOS, Windows y Linux que miden una mezcla contra las especificaciones de Netflix, Amazon, Disney+, EBU R 128 o de tr\u00e1iler de cine, se\u00f1alan la cl\u00e1usula que falla, la citan y sugieren el arreglo. Medidores de loudness y true peak BS.1770-5 escritos desde el est\u00e1ndar, que pasan los 29 casos de prueba de la EBU; 39 perfiles de destino, 190 pruebas y un diff de audio que reporta desfase, ganancia, polaridad y residual.',
    status_en: '2026', status_es: '2026',
    stack: JSON.stringify(['Python', 'NumPy', 'SciPy', 'libsndfile', 'Typer', 'Pydantic', 'AppleScript']),
    category_en: 'Audio Software', category_es: 'Software de Audio',
    gallery_id: null,
    link: 'https://github.com/victor10days/cumple',
  },
  // --- Full-Stack Development ---
  {
    name_en: 'Bellonera', name_es: 'Bellonera',
    desc_en: 'Song auction for bars and the DJs who play them: guests scan a code, search any song and bid from $3, and the room watches the bid on the big screen while a three-minute clock extends 20 seconds on every late bid. Three surfaces (guest phone, big screen, DJ console), and the winner is charged only when the DJ marks the song played; payments are simulated in this build.',
    desc_es: 'Subasta de canciones para bares y para los DJ que ponen la m\u00fasica: el p\u00fablico escanea un c\u00f3digo, busca cualquier canci\u00f3n y puja desde $3, y la sala ve la puja en la pantalla grande mientras un reloj de tres minutos se extiende 20 segundos con cada puja de \u00faltimo minuto. Tres pantallas (el celular del p\u00fablico, la pantalla grande y la consola del DJ), y al ganador se le cobra solo cuando el DJ marca la canci\u00f3n como tocada; los pagos est\u00e1n simulados en esta versi\u00f3n.',
    status_en: '2026 \u00b7 live', status_es: '2026 \u00b7 en producci\u00f3n',
    stack: JSON.stringify(['Python', 'FastAPI', 'SQLAlchemy', 'Alembic', 'PostgreSQL', 'SSE', 'TypeScript', 'React', 'Vite', 'Playwright', 'Render']),
    category_en: 'Full-Stack Development', category_es: 'Desarrollo Full-Stack',
    gallery_id: null,
    link: 'https://bellonera-app.onrender.com',
  },
  {
    name_en: 'Regulatory Records Extractor', name_es: 'Extractor de Registros Regulatorios',
    desc_en: 'Pulls structured regulatory records out of long environmental PDFs: an async job queue behind a REST API, chunked processing with retry and backoff, schema-validated model output, and cost reported per job.',
    desc_es: 'Extrae registros regulatorios estructurados de PDFs ambientales largos: una cola de trabajos as\u00edncrona detr\u00e1s de una API REST, procesamiento por bloques con reintentos y backoff, salida del modelo validada por esquema y costo reportado por trabajo.',
    status_en: '2026', status_es: '2026',
    stack: JSON.stringify(['Python', 'FastAPI', 'Anthropic API', 'pdfplumber', 'Pydantic']),
    category_en: 'Full-Stack Development', category_es: 'Desarrollo Full-Stack',
    gallery_id: null,
    link: null,
  },
  {
    name_en: 'HBnB Evolution', name_es: 'HBnB Evolution',
    desc_en: 'Complete full-stack rental platform with user authentication, property management, and review system.',
    desc_es: 'Plataforma de alquiler full-stack completa con autenticación de usuarios, gestión de propiedades y sistema de reseñas.',
    status_en: 'December 2025', status_es: 'Diciembre 2025',
    stack: JSON.stringify(['Python', 'Flask', 'HTML/CSS', 'JavaScript', 'SQL']),
    category_en: 'Full-Stack Development', category_es: 'Desarrollo Full-Stack',
    gallery_id: null,
    link: 'https://github.com/victor10days/holbertonschool-hbnb',
  },
  {
    name_en: 'AI Business Process Optimizer', name_es: 'Optimizador de Procesos con IA',
    desc_en: 'Enterprise Odoo 16.0 ERP add-on for automated process analysis and optimization using multi-provider AI integration.',
    desc_es: 'Módulo empresarial para Odoo 16.0 que analiza y optimiza procesos de negocio mediante integración de IA multi-proveedor.',
    status_en: '2025', status_es: '2025',
    stack: JSON.stringify(['Python', 'Odoo 16', 'Anthropic API', 'OpenAI API']),
    category_en: 'Full-Stack Development', category_es: 'Desarrollo Full-Stack',
    gallery_id: null,
    link: 'https://github.com/victor10days/apexive-hackaton-odoo',
  },
  {
    name_en: 'Simple Shell', name_es: 'Simple Shell',
    desc_en: 'A lightweight UNIX command interpreter written in C for educational purposes.',
    desc_es: 'Un intérprete de comandos UNIX ligero escrito en C con fines educativos.',
    status_en: 'March 2025', status_es: 'Marzo 2025',
    stack: JSON.stringify(['C', 'UNIX', 'System Calls']),
    category_en: 'Full-Stack Development', category_es: 'Desarrollo Full-Stack',
    gallery_id: null,
    link: 'https://github.com/victor10days/holbertonschool-simple_shell',
  },
  {
    name_en: 'Printf', name_es: 'Printf',
    desc_en: 'Custom implementation of the standard C library function printf.',
    desc_es: 'Implementación personalizada de la función printf de la biblioteca estándar de C.',
    status_en: 'February 2025', status_es: 'Febrero 2025',
    stack: JSON.stringify(['C', 'Variadic Functions']),
    category_en: 'Full-Stack Development', category_es: 'Desarrollo Full-Stack',
    gallery_id: null,
    link: 'https://github.com/victor10days/holbertonschool-low_level_programming',
  },
];

// Experience data
const experience = [
  {
    role_en: 'Jr. Software Engineer', role_es: 'Ingeniero de Software Jr.',
    company_en: 'Ama Earth Group', company_es: 'Ama Earth Group',
    date_en: 'May 2026 – July 2026', date_es: 'Mayo 2026 – Julio 2026',
    desc_en: 'Built and shipped the AI features of an environmental-report platform used by consultants: LLM-driven report generation, Claude-based agents and SAM2 parcel detection, on FastAPI services in Docker over PostgreSQL/PostGIS behind GitHub Actions CI. Owned evaluation: ground-truth datasets and IoU/precision/recall harnesses scoring automated output against human analysts, about 80% agreement, measured before every release.',
    desc_es: 'Construí y lancé las funcionalidades de IA de una plataforma de informes ambientales usada por consultores: generación de informes con LLMs, agentes basados en Claude y detección de parcelas con SAM2, sobre servicios FastAPI en Docker con PostgreSQL/PostGIS e integración continua en GitHub Actions. Me encargué de la evaluación: conjuntos de datos de referencia y pruebas de IoU/precisión/recall que comparaban la salida automatizada con la de analistas humanos, cerca de 80% de coincidencia, medidas antes de cada lanzamiento.',
  },
  {
    role_en: 'Studio Engineer', role_es: 'Ingeniero de Estudio',
    company_en: 'Paleta Creativa', company_es: 'Paleta Creativa',
    date_en: '2025 – June 2026', date_es: '2025 – Junio 2026',
    desc_en: 'Clients include Warner Bros, Caribbean Cinemas, GFR Media, Mobil.',
    desc_es: 'Clientes incluyen Warner Bros, Caribbean Cinemas, GFR Media, Mobil.',
  },
  {
    role_en: 'Architectural Documentation Assistant', role_es: 'Asistente de Documentación Arquitectónica',
    company_en: 'Díaz Paunetto Architects', company_es: 'Díaz Paunetto Arquitectos',
    date_en: '2024 – 2025', date_es: '2024 – 2025',
    desc_en: 'Restoration documentation for Museo Casa Roig.',
    desc_es: 'Documentación de restauración del Museo Casa Roig.',
  },
  {
    role_en: 'Event Producer', role_es: 'Productor de Eventos',
    company_en: "'Toma Control' Interactive Event", company_es: "Evento Interactivo 'Toma Control'",
    date_en: '2024', date_es: '2024',
    desc_en: 'Collaboration with Coca-Cola, Cuadrado Gris, Radio Underground.',
    desc_es: 'Colaboración con Coca-Cola, Cuadrado Gris, Radio Underground.',
  },
  {
    role_en: 'Sound Designer', role_es: 'Diseñador de Sonido',
    company_en: 'Adelobo Estudios', company_es: 'Adelobo Estudios',
    date_en: '2024', date_es: '2024',
    desc_en: 'Sound design work in Santo Domingo, DR.',
    desc_es: 'Trabajo de diseño sonoro en Santo Domingo, RD.',
  },
  {
    role_en: 'Music Teacher', role_es: 'Profesor de Música',
    company_en: 'MAC: Ética y Reggaetón', company_es: 'MAC: Ética y Reggaetón',
    date_en: '2023 – 2024', date_es: '2023 – 2024',
    desc_en: 'Barrio Obrero en el Microphone program, San Juan.',
    desc_es: 'Programa Barrio Obrero en el Microphone, San Juan.',
  },
  {
    role_en: 'Data Entry', role_es: 'Data Entry',
    company_en: 'CENCOR', company_es: 'CENCOR',
    date_en: '2023 – 2024', date_es: '2023 – 2024',
    desc_en: 'The Data Technician supports the Historic Buildings and Sites Division by entering, organizing, verifying, and backing up project data while assisting coordinators with scheduling and taking on additional tasks as needed.',
    desc_es: 'El técnico de datos presta apoyo a la División de Edificios y Sitios Históricos introduciendo, organizando, verificando y realizando copias de seguridad de los datos de los proyectos, a la vez que ayuda a los coordinadores con la programación y asume tareas adicionales según sea necesario.',
  },
  {
    role_en: 'Sound Designer', role_es: 'Diseñador de Sonido',
    company_en: 'Caribbean Cinemas', company_es: 'Caribbean Cinemas',
    date_en: '2022', date_es: '2022',
    desc_en: 'Sound design for the Caribbean Cinemas policy trailer.',
    desc_es: 'Diseño sonoro para el trailer de políticas de Caribbean Cinemas.',
  },
];

export { gallery, projects, experience };
